# version: "3.9"
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: creditdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    healthcheck: # ✅ ensure MySQL is ready before API starts
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "user",
          "--password=password",
        ]
      interval: 5s
      timeout: 10s
      retries: 5
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy # ✅ wait for db to pass healthcheck
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: creditdb
